Get http://localhost:4000/ping

###
Post http://localhost:4000/auth/login
content-type: application/json

{   
    "email": "rafaell@teste.com.br",
    "senha": "#Senha1234!"
}

###
Post http://localhost:4000/auth/registrar
content-type: application/json

{   
     "nome": "Leonardo Costa",
     "email": "lc@teste.com.br",
     "senha": "#Senha1234", 
     "telefone": "+55999992211"    
}

###
Post http://localhost:4000/auth/apagar
content-type: application/json

{   
     "nome": "Marcia Abreu",
     "email": "marciaabreu@teste.com.br",
     "senha": "#Senha1234!"
}

# {
   
#     "nome": "Rafael Lima",
#     "email": "rafaell@teste.com.br",
#     "senha": "#Senha1234!"
# }

###
Post http://localhost:4000/auth/editar
content-type: application/json

{   
     "nome": "Marcia Abreu Lima",
     "email": "marciaabreu@teste.com.br",
     "senha": "#Senha1234!"
}

###
Post http://localhost:4000/auth/recuperarSenha
content-type: application/json

{        
     "email": "lc@teste.com.br"
}


###
GET  http://localhost:4000/administracao
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU1NjFiODFjLWI0ZjMtNGY1NS05ZjgzLTRkNzQ1NTRjMGI0MyIsIm5vbWUiOiJSYWZhZWwgTGltYSIsImVtYWlsIjoicmFmYWVsbEB0ZXN0ZS5jb20uYnIiLCJpYXQiOjE3MzQ4OTQxNjgsImV4cCI6MTczNjE5MDE2OH0.p-Pz7yaxIbVlR9dsfKfqdv6YqlVDz8pU4LmHg_7u94Q
